export * from './app.module';
export * from './campus.module';
export * from './database.module';
export * from './evaluation.module';
export * from './services.module';
export * from './websocket.module';
export * from './course.module';
export * from './professor.module';
export * from './security.module';